---
services:
  pastentonne:
    container_name: pastentonne
    restart: unless-stopped
    build:
      context: ..
      dockerfile: ./docker/app.Dockerfile
      args:
        TIMEZONE: ${TIMEZONE:?error}
        UID: ${UID:?error}
        GID: ${GID:?error}
        NUXT_DATA_DIR: ${NUXT_DATA_DIR:?error}
    env_file:
      - ../.env
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ../.data:${NUXT_DATA_DIR:?error}
